/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import {
  Device,
  WorkOrder,
  SecurityCamera,
  AlertLog,
  FireEquipment,
  DoorLog,
  ElectronicFence,
  ProductionOrder,
  MaintenanceRecord,
  MoldChangeRecord,
  SafetyEvent,
  ProductionOverview,
  ProcessStep,
  ProductionLineMetrics,
  QualityTrace,
  WipZone,
  BottleneckHeatCell,
  EnergyOverviewSnapshot,
  EnergyDeviceProfile,
  EnergyZoneProfile,
  EnergyAlertItem,
  EnergyCapacityLink,
  EnergySavingTip,
  EnergyTrendPoint,
} from './types';

const defaultThresholds = (temp: number, tensionMin: number, tensionMax: number, speed: number, pressure: number, load: number) => ({
  temperatureMax: temp,
  tensionMin,
  tensionMax,
  speedMax: speed,
  pressureMax: pressure,
  loadMax: load,
});

export const INITIAL_DEVICES: Device[] = [
  {
    id: 'dev-01',
    name: '直进式拉丝机 #01',
    code: 'LSJ-001',
    area: '一车间 拉丝区 A',
    type: 'pulling_machine',
    process: '拉丝',
    temperature: 58.4,
    tension: 41.2,
    speed: 450,
    pressure: 0.32,
    load: 68,
    frequency: 50.0,
    health: 96,
    status: 'success',
    model: 'LS-200X',
    lastMaintenance: '2026-05-15',
    cycleDays: 30,
    moldCode: 'MOLD-D04',
    moldWear: 42,
    faultCountWeek: 0,
    runHours: 4280,
    thresholds: defaultThresholds(85, 38, 55, 500, 0.45, 90),
    focus3d: { offsetX: 90, offsetY: 50, scale: 1.1 },
  },
  {
    id: 'dev-02',
    name: '双盘收线机 #02',
    code: 'SXJ-002',
    area: '一车间 收线区 B',
    type: 'winding_machine',
    process: '收放线',
    temperature: 63.8,
    tension: 38.5,
    speed: 380,
    pressure: 0.28,
    load: 72,
    frequency: 48.5,
    health: 78,
    status: 'warning',
    model: 'SX-400A',
    lastMaintenance: '2026-05-01',
    cycleDays: 30,
    moldCode: 'MOLD-W12',
    moldWear: 85,
    faultCountWeek: 2,
    runHours: 5120,
    thresholds: defaultThresholds(75, 32, 50, 420, 0.35, 85),
    focus3d: { offsetX: 40, offsetY: -30, scale: 1.08 },
  },
  {
    id: 'dev-03',
    name: '高速行星成缆机 #03',
    code: 'CLJ-003',
    area: '二车间 束绞区 B',
    type: 'cable_strander',
    process: '成缆',
    temperature: 215.3,
    tension: 43.8,
    speed: 92,
    pressure: 2.15,
    load: 83,
    frequency: 35.2,
    health: 45,
    status: 'error',
    model: 'CL-800',
    lastMaintenance: '2026-04-10',
    cycleDays: 45,
    moldCode: 'MOLD-C08',
    moldWear: 68,
    faultCountWeek: 5,
    runHours: 3890,
    thresholds: defaultThresholds(200, 35, 48, 150, 2.5, 95),
    focus3d: { offsetX: -20, offsetY: 45, scale: 1.15 },
  },
  {
    id: 'dev-04',
    name: '精密绝缘挤塑机 #04',
    code: 'JSX-004',
    area: '二车间 挤出区 C',
    type: 'extruder',
    process: '挤塑',
    temperature: 182.5,
    tension: 24.1,
    speed: 120,
    pressure: 3.84,
    load: 91,
    frequency: 42.0,
    health: 85,
    status: 'bottleneck',
    model: 'JS-120/25',
    lastMaintenance: '2026-05-20',
    cycleDays: 60,
    moldCode: 'MOLD-E21',
    moldWear: 55,
    faultCountWeek: 1,
    runHours: 6010,
    thresholds: defaultThresholds(195, 18, 35, 140, 4.2, 95),
    focus3d: { offsetX: -70, offsetY: 60, scale: 1.08 },
  },
  {
    id: 'dev-05',
    name: '自动护套挤出机 #05',
    code: 'JSX-005',
    area: '二车间 挤出区 D',
    type: 'extruder',
    process: '挤塑',
    temperature: 42.1,
    tension: 0.0,
    speed: 0,
    pressure: 0.05,
    load: 4,
    frequency: 0,
    health: 92,
    status: 'idle',
    model: 'JS-150D',
    lastMaintenance: '2026-05-10',
    cycleDays: 60,
    moldCode: 'MOLD-E33',
    moldWear: 22,
    faultCountWeek: 0,
    runHours: 2100,
    thresholds: defaultThresholds(190, 15, 30, 130, 4.0, 90),
    focus3d: { offsetX: -100, offsetY: -20, scale: 1.06 },
  },
];

export const INITIAL_WORK_ORDERS: WorkOrder[] = [
  {
    id: 'WO-260609-01',
    deviceCode: 'CLJ-003',
    deviceName: '高速行星成缆机 #03',
    title: '温控传感器故障，冷却水路堵塞排查',
    type: '紧急抢修',
    priority: 'P1',
    assignee: '张工 (高级维护员)',
    status: '待派发',
    createdAt: '09:12',
    description: '成缆段主轴承外圈温度持续超过200°C触发停机保护线圈，疑似冷却回路流通不畅，急需现场更换温控探针并疏通冷却阀口。',
  },
  {
    id: 'WO-260608-04',
    deviceCode: 'LSJ-001',
    deviceName: '直进式拉丝机 #01',
    title: '定期磨损核查与一号拉丝模具更换',
    type: '预防维保',
    priority: 'P3',
    assignee: '李工 (设备班长)',
    status: '处理中',
    createdAt: '昨日 14:30',
    description: '拉丝拉削受力偏差略有上升，模具 D-04 已经运行180小时，磨损计分达85%，计划停歇15分钟更换全新耐磨合金拉模。',
  },
];

export const INITIAL_CAMERAS: SecurityCamera[] = [
  {
    id: 'cam-01',
    name: '一车间北门大通道',
    code: 'CAM-GATE-01',
    area: '工厂主入口',
    zone: '大门',
    status: 'online',
    streamUrl: 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=420&q=70',
    heading: -45,
    activeDetections: ['常规车流', '人员考勤中'],
    pos3d: { left: 90, top: 140, z: 30 },
    focus3d: { offsetX: 60, offsetY: 30, scale: 1.08 },
  },
  {
    id: 'cam-02',
    name: '危化品仓库东侧围栏',
    code: 'CAM-CHEM-02',
    area: '危化品库特种防爆区',
    zone: '危化区',
    status: 'online',
    streamUrl: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=420&q=70',
    heading: 60,
    activeDetections: ['电子围栏激活', '闯入侦测'],
    pos3d: { left: 310, top: 470, z: 40 },
    focus3d: { offsetX: 20, offsetY: -40, scale: 1.12 },
  },
  {
    id: 'cam-03',
    name: '二车间成缆组核心区域',
    code: 'CAM-CABLE-03',
    area: '成缆及收线组工艺走廊',
    zone: '成缆区',
    status: 'online',
    streamUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=420&q=70',
    heading: 15,
    activeDetections: ['安全帽AI监测', '高温风险挂账'],
    pos3d: { left: 540, top: 180, z: 35 },
    focus3d: { offsetX: -30, offsetY: 20, scale: 1.1 },
  },
  {
    id: 'cam-04',
    name: '拉丝A区作业面',
    code: 'CAM-DRAW-04',
    area: '一车间 拉丝区 A',
    zone: '车间',
    status: 'online',
    streamUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=420&q=70',
    heading: 10,
    activeDetections: ['作业区监控'],
    pos3d: { left: 160, top: 280, z: 30 },
    focus3d: { offsetX: 50, offsetY: 10, scale: 1.06 },
  },
  {
    id: 'cam-05',
    name: '挤出高温熔融段',
    code: 'CAM-EXT-05',
    area: '二车间 挤出区 C',
    zone: '车间',
    status: 'online',
    streamUrl: 'https://images.unsplash.com/photo-1565793298595-6a879b1d9492?auto=format&fit=crop&w=420&q=70',
    heading: 25,
    activeDetections: ['高温区监控', '防灼围栏联动'],
    pos3d: { left: 720, top: 200, z: 32 },
    focus3d: { offsetX: -60, offsetY: 15, scale: 1.08 },
  },
  {
    id: 'cam-06',
    name: '南门访客登记通道',
    code: 'CAM-GATE-06',
    area: '南门访客翼闸',
    zone: '大门',
    status: 'offline',
    streamUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=420&q=70',
    heading: 0,
    activeDetections: ['离线检修中'],
    pos3d: { left: 420, top: 520, z: 28 },
    focus3d: { offsetX: 0, offsetY: -50, scale: 1.05 },
  },
];

export const INITIAL_ALERTS: AlertLog[] = [
  {
    id: 'AL-1001',
    level: 'P1严重',
    category: 'operations',
    title: '成缆机 #03 温度超限 (运行温度 215.3°C)',
    description: '主温控线超标触发系统紧急中断，检测值：215.3°C (标准温区 ≤ 200.0°C)。',
    location: '二车间 束绞区 B组',
    time: '09:12:05',
    status: 'pending',
    deviceCode: 'CLJ-003',
  },
  {
    id: 'AL-1002',
    level: 'P2高危',
    category: 'security',
    title: '危化品仓库电子围栏报警 (触发入侵)',
    description: 'CAM-CHEM-02 视频流智能识别：外协人员短暂翻越警戒线，疑似设备备件运输越区。',
    location: '一车间 B区后通道 绝缘料库',
    time: '09:28:40',
    status: 'pending',
    cameraId: 'cam-02',
    fenceId: 'fence-01',
    securityKind: 'intrusion',
    focus3d: { offsetX: 25, offsetY: -35, scale: 1.12 },
  },
  {
    id: 'AL-1005',
    level: 'P2高危',
    category: 'security',
    title: '成缆区违规作业 — 未佩戴安全帽',
    description: 'CAM-CABLE-03 AI 识别：作业人员进入成缆走廊时安全帽检测未通过，已联动语音提醒。',
    location: '二车间 成缆组工艺走廊',
    time: '09:35:18',
    status: 'pending',
    cameraId: 'cam-03',
    securityKind: 'violation',
    focus3d: { offsetX: -25, offsetY: 25, scale: 1.1 },
  },
  {
    id: 'AL-1006',
    level: 'P3一般',
    category: 'security',
    title: '挤出高温区烟感读数波动',
    description: 'SD-86 烟感探测器短时读数升高，CAM-EXT-05 画面未见明火，建议现场复核。',
    location: '二车间 挤出高温熔融区',
    time: '08:52:11',
    status: 'pending',
    cameraId: 'cam-05',
    fenceId: 'fence-02',
    securityKind: 'fire',
    focus3d: { offsetX: -55, offsetY: 10, scale: 1.08 },
  },
  {
    id: 'AL-1003',
    level: 'P2高危',
    category: 'production',
    title: '工单 SO-260609-18 生产瓶颈',
    description: '成缆机故障中断导致护套工序待料停机，OEE降至72%，触发交付滞延警示。',
    location: '二车间 束绞→护套生产组',
    time: 'Yesterday 14:30',
    status: 'pending',
    deviceCode: 'CLJ-003',
  },
  {
    id: 'AL-1004',
    level: 'P3一般',
    category: 'energy',
    title: '退火炉 #02 峰段耗功率异常攀升',
    description: '配电智能网关监测：退火加热丝在尖峰电价区间运行突增25kW异常谐波，负荷调配失效。',
    location: '一车间 铜拉退火组',
    time: 'Yesterday 11:20',
    status: 'pending',
  },
];

export const INITIAL_FIRE_EQUIPMENT: FireEquipment[] = [
  {
    id: 'fire-01',
    name: '主消防消火栓 #F-01',
    code: 'FH-01',
    area: '一车间拉丝A区柱侧',
    status: '正常',
    lastChecked: '2026-06-05',
    cycleDays: 30,
    type: 'hydrant',
    pos3d: { left: 120, top: 320, z: 25 },
    lastMaintSummary: '2026-06-05 水压检测正常',
  },
  {
    id: 'fire-02',
    name: '二氧化碳防爆灭火器 #E-14',
    code: 'FE-14',
    area: '危化品绝缘料库大门',
    status: '待巡检',
    lastChecked: '2026-05-18',
    cycleDays: 15,
    type: 'fire_extinguisher',
    pos3d: { left: 260, top: 140, z: 35 },
    lastMaintSummary: '压力表待复核',
  },
  {
    id: 'fire-03',
    name: '红外光电感烟探测器 #S-86',
    code: 'SD-86',
    area: '二车间天花吊顶部',
    status: '正常',
    lastChecked: '2026-06-02',
    cycleDays: 30,
    type: 'smoke_sensor',
    pos3d: { left: 680, top: 120, z: 20 },
    lastMaintSummary: '2026-06-02 灵敏度校准',
  },
  {
    id: 'fire-04',
    name: '高阻安全排烟温感 #T-02',
    code: 'TD-02',
    area: '挤出高温熔融区',
    status: '待巡检',
    lastChecked: '2026-05-12',
    cycleDays: 20,
    type: 'smoke_sensor',
    pos3d: { left: 750, top: 250, z: 28 },
    lastMaintSummary: '温感探头待更换',
  },
  {
    id: 'fire-05',
    name: '干粉灭火器 #E-22',
    code: 'FE-22',
    area: '成缆组工艺走廊',
    status: '正常',
    lastChecked: '2026-06-08',
    cycleDays: 15,
    type: 'fire_extinguisher',
    pos3d: { left: 500, top: 200, z: 30 },
    lastMaintSummary: '2026-06-08 压力正常',
  },
];

export const INITIAL_DOOR_LOGS: DoorLog[] = [
  {
    id: 'log-01',
    name: '周建平',
    avatar: '👩‍🔧',
    role: '员工',
    action: '进入',
    location: '二车间 一号人行翼闸',
    time: '09:35:12',
    status: 'success',
  },
  {
    id: 'log-02',
    name: '程工',
    avatar: '👨‍🔧',
    role: '主管',
    action: '进入',
    location: '北门车辆一卡通主桥',
    time: '09:33:04',
    status: 'success',
  },
  {
    id: 'log-03',
    name: '外协维保043',
    avatar: '🕵️',
    role: '外协人员',
    action: '登记',
    location: '北门外访自助登记终端',
    time: '09:25:40',
    status: 'success',
  },
  {
    id: 'log-04',
    name: '未知外协人员',
    avatar: '⚠️',
    role: '外协人员',
    action: '进入',
    location: '危化料库防护翼闸',
    time: '09:28:40',
    status: 'warning',
  },
];

export const INITIAL_FENCES: ElectronicFence[] = [
  {
    id: 'fence-01',
    name: '化学危险品储料库电子围栏',
    area: '绝缘材料仓库核心圈',
    fenceType: '危化品仓库',
    status: 'active',
    intrusionAlert: true,
    color: 'rgba(239, 68, 68, 0.4)',
    pos3d: { left: 40, bottom: 40, width: 300, height: 180 },
    linkedCameraId: 'cam-02',
    focus3d: { offsetX: 25, offsetY: -35, scale: 1.12 },
  },
  {
    id: 'fence-02',
    name: '挤出机熔融段高温防灼围栏',
    area: '挤出高温主机15米范围',
    fenceType: '高温区',
    status: 'active',
    intrusionAlert: false,
    color: 'rgba(245, 158, 11, 0.3)',
    pos3d: { left: 620, bottom: 40, width: 320, height: 140 },
    linkedCameraId: 'cam-05',
    focus3d: { offsetX: -55, offsetY: 10, scale: 1.08 },
  },
  {
    id: 'fence-03',
    name: '成缆机械作业区防护围栏',
    area: '成缆组旋转部件15米范围',
    fenceType: '机械作业区',
    status: 'active',
    intrusionAlert: false,
    color: 'rgba(99, 102, 241, 0.3)',
    pos3d: { left: 380, bottom: 120, width: 280, height: 160 },
    linkedCameraId: 'cam-03',
    focus3d: { offsetX: -25, offsetY: 25, scale: 1.1 },
  },
];

export const INITIAL_SAFETY_EVENTS: SafetyEvent[] = [
  {
    id: 'SE-01',
    title: '危化品库电子围栏越界闯入',
    type: '区域闯入',
    time: '2026-06-09 09:28',
    location: '绝缘材料仓库核心圈',
    status: '处置中',
    handler: '安防值班组',
    process: '已联动 CAM-CHEM-02 抓拍存证，巡逻队已赶赴现场复核，外协人员已带离。',
  },
  {
    id: 'SE-02',
    title: '成缆走廊安全帽违规',
    type: '违规作业',
    time: '2026-06-09 09:35',
    location: '二车间成缆组',
    status: '处置中',
    handler: '产线班长',
    process: 'AI 语音提醒已下发，当事人已补戴安全帽，班前教育记录已登记。',
  },
  {
    id: 'SE-03',
    title: '北门访客通道异常滞留',
    type: '其他',
    time: '2026-06-08 16:20',
    location: '南门访客翼闸',
    status: '已闭环',
    handler: '门卫组',
    process: '访客登记信息核对完毕，已正常放行。',
    rectification: '加强访客引导标识，高峰时段增派引导员。',
  },
  {
    id: 'SE-04',
    title: '灭火器 E-14 压力不足预警',
    type: '消防异常',
    time: '2026-06-07 10:15',
    location: '危化品库大门',
    status: '已闭环',
    handler: '消防维保组',
    process: '现场更换灭火器并更新台账。',
    rectification: '巡检周期由30天缩短至15天。',
  },
];

export const INITIAL_PRODUCTION_ORDERS: ProductionOrder[] = [
  {
    id: 'SO-260609-18',
    productType: '高压阻燃交联线缆 YJV-3x240',
    batchNo: 'BATCH-20260609-A18',
    currentProcess: '绝缘',
    completionRate: 76,
    plannedQty: 24.5,
    completedQty: 18.62,
    status: 'bottleneck',
    orderStatus: 'in_progress',
    deliveryTime: '2026-06-12 18:00',
    oee: 72,
    qualityRate: 98.6,
  },
  {
    id: 'SO-260609-21',
    productType: '家装BV硬导线 BV-2.5',
    batchNo: 'BATCH-20260609-B21',
    currentProcess: '绝缘',
    completionRate: 58,
    plannedQty: 80.0,
    completedQty: 46.4,
    status: 'normal',
    orderStatus: 'in_progress',
    deliveryTime: '2026-06-11 12:00',
    oee: 88,
    qualityRate: 99.4,
  },
  {
    id: 'SO-260609-25',
    productType: '电力低烟无卤 WDZ-BYJ',
    batchNo: 'BATCH-20260609-C25',
    currentProcess: '拉丝',
    completionRate: 32,
    plannedQty: 12.0,
    completedQty: 3.84,
    status: 'normal',
    orderStatus: 'in_progress',
    deliveryTime: '2026-06-13 08:00',
    oee: 84,
    qualityRate: 99.1,
  },
  {
    id: 'SO-260608-11',
    productType: '控制电缆 KVVP-4x1.5',
    batchNo: 'BATCH-20260608-D11',
    currentProcess: '成卷',
    completionRate: 100,
    plannedQty: 6.0,
    completedQty: 6.0,
    status: 'normal',
    orderStatus: 'qc_pending',
    deliveryTime: '2026-06-10 16:00',
    oee: 91,
    qualityRate: 99.6,
  },
];

export const PRODUCTION_OVERVIEW: ProductionOverview = {
  shiftOutputKm: 18.62,
  dailyOutputKm: 42.8,
  orderCompletionRate: 82,
  overallYield: 98.9,
  avgOee: 81.2,
  totalWireBreaks: 7,
  dailyPlanProgress: 82,
};

export const INITIAL_PROCESS_STEPS: ProcessStep[] = [
  {
    id: 'drawing',
    label: '拉丝',
    deviceCode: 'LSJ-001',
    deviceName: '直进式拉丝机 #01',
    status: 'running',
    wipQty: 2.4,
    wipUnit: 'km',
    orderId: 'SO-260609-18',
    lineSpeed: 450,
    defectRate: 0.9,
    wireBreakCount: 1,
    focus3d: { offsetX: 90, offsetY: 50, scale: 1.1 },
    bayRegion: { left: 24, top: 120, width: 200, height: 200 },
  },
  {
    id: 'stranding',
    label: '绞线',
    deviceCode: 'CLJ-003',
    deviceName: '高速行星成缆机 #03',
    status: 'stopped',
    wipQty: 1.8,
    wipUnit: 'km',
    orderId: 'SO-260609-18',
    lineSpeed: 0,
    defectRate: 2.1,
    wireBreakCount: 3,
    focus3d: { offsetX: -20, offsetY: 45, scale: 1.15 },
    bayRegion: { left: 320, top: 100, width: 240, height: 220 },
  },
  {
    id: 'insulation',
    label: '绝缘',
    deviceCode: 'JSX-004',
    deviceName: '精密绝缘挤塑机 #04',
    status: 'blocked',
    wipQty: 0.6,
    wipUnit: 'km',
    orderId: 'SO-260609-18',
    lineSpeed: 45,
    defectRate: 1.4,
    wireBreakCount: 0,
    focus3d: { offsetX: -70, offsetY: 60, scale: 1.08 },
    bayRegion: { left: 620, top: 80, width: 200, height: 180 },
  },
  {
    id: 'sheathing',
    label: '护套',
    deviceCode: 'JSX-005',
    deviceName: '自动护套挤出机 #05',
    status: 'idle',
    wipQty: 0,
    wipUnit: 'km',
    orderId: 'SO-260609-18',
    lineSpeed: 0,
    defectRate: 0,
    wireBreakCount: 0,
    focus3d: { offsetX: -100, offsetY: -20, scale: 1.06 },
    bayRegion: { left: 720, top: 240, width: 180, height: 160 },
  },
  {
    id: 'winding',
    label: '收线',
    deviceCode: 'SXJ-002',
    deviceName: '双盘收线机 #02',
    status: 'running',
    wipQty: 3.2,
    wipUnit: 'km',
    orderId: 'SO-260609-21',
    lineSpeed: 380,
    defectRate: 0.6,
    wireBreakCount: 2,
    focus3d: { offsetX: 40, offsetY: -30, scale: 1.08 },
    bayRegion: { left: 260, top: 280, width: 180, height: 140 },
  },
];

export const INITIAL_LINE_METRICS: ProductionLineMetrics[] = [
  { lineId: 'L1', lineName: '拉丝 A 线', deviceCode: 'LSJ-001', outputKm: 8.2, lineSpeed: 450, wireBreakCount: 1, defectRate: 0.9, oee: 89, effectiveRunHours: 6.2, idleRatio: 8, downtimeRatio: 3 },
  { lineId: 'L2', lineName: '成缆 B 线', deviceCode: 'CLJ-003', outputKm: 4.1, lineSpeed: 0, wireBreakCount: 3, defectRate: 2.1, oee: 42, effectiveRunHours: 2.8, idleRatio: 15, downtimeRatio: 43 },
  { lineId: 'L3', lineName: '绝缘 C 线', deviceCode: 'JSX-004', outputKm: 3.6, lineSpeed: 45, defectRate: 1.4, wireBreakCount: 0, oee: 68, effectiveRunHours: 5.1, idleRatio: 22, downtimeRatio: 10 },
  { lineId: 'L4', lineName: '护套 D 线', deviceCode: 'JSX-005', outputKm: 0.8, lineSpeed: 0, wireBreakCount: 0, defectRate: 0, oee: 35, effectiveRunHours: 1.2, idleRatio: 58, downtimeRatio: 7 },
  { lineId: 'L5', lineName: '收线 E 线', deviceCode: 'SXJ-002', outputKm: 6.4, lineSpeed: 380, wireBreakCount: 2, defectRate: 0.6, oee: 86, effectiveRunHours: 5.8, idleRatio: 10, downtimeRatio: 4 },
];

export const INITIAL_QUALITY_TRACES: QualityTrace[] = [
  // —— BATCH-20260609-A18 全工序追溯链（主异常批次）——
  {
    id: 'QT-A18-01',
    batchNo: 'BATCH-20260609-A18',
    orderId: 'SO-260609-18',
    productType: 'YJV-3x240',
    processStep: 'drawing',
    processLabel: '拉丝',
    deviceCode: 'LSJ-001',
    deviceName: '直进式拉丝机 #01',
    operator: '王工',
    shift: '白班',
    startTime: '06:00',
    endTime: '08:30',
    timeRange: '06:00 — 08:30',
    sampleNo: 'SP-A18-LS-01',
    result: 'pass',
    params: [
      { label: '拉丝张力', value: '41.2 N', standard: '38 — 55 N', normal: true },
      { label: '线速度', value: '450 m/min', standard: '400 — 500 m/min', normal: true },
      { label: '铜杆直径', value: '8.0 mm', standard: '7.9 — 8.1 mm', normal: true },
      { label: '断线次数', value: '1 次', standard: '≤ 2 次/班', normal: true },
    ],
  },
  {
    id: 'QT-A18-02',
    batchNo: 'BATCH-20260609-A18',
    orderId: 'SO-260609-18',
    productType: 'YJV-3x240',
    processStep: 'stranding',
    processLabel: '绞线/成缆',
    deviceCode: 'CLJ-003',
    deviceName: '高速行星成缆机 #03',
    operator: '张工 / 陈师傅',
    shift: '白班',
    startTime: '08:45',
    endTime: '09:35',
    timeRange: '08:45 — 09:35',
    sampleNo: 'SP-A18-CJ-01',
    result: 'fail',
    params: [
      { label: '束绞张力', value: '43.8 N', standard: '35 — 48 N', normal: true },
      { label: '主轴温度', value: '215.3 °C', standard: '≤ 200 °C', normal: false },
      { label: '线速度', value: '92 rpm', standard: '80 — 150 rpm', normal: true },
      { label: '节距偏差', value: '±1.8 mm', standard: '±1.0 mm', normal: false },
    ],
    anomaly: '主轴热保护触发停机，冷却回路流通不畅导致超温，节距稳定性下降',
    correctiveAction: '已下发抢修工单 WO-260609-01，待更换温控探针并疏通冷却阀',
  },
  {
    id: 'QT-A18-03',
    batchNo: 'BATCH-20260609-A18',
    orderId: 'SO-260609-18',
    productType: 'YJV-3x240',
    processStep: 'insulation',
    processLabel: '绝缘',
    deviceCode: 'JSX-004',
    deviceName: '精密绝缘挤塑机 #04',
    operator: '赵工',
    shift: '白班',
    startTime: '07:30',
    endTime: '09:00',
    timeRange: '07:30 — 09:00（待料暂停）',
    sampleNo: 'SP-A18-JY-01',
    result: 'warning',
    params: [
      { label: '绝缘厚度', value: '1.15 mm', standard: '1.2 ±0.1 mm', normal: true },
      { label: '挤出温度', value: '182.5 °C', standard: '175 — 195 °C', normal: true },
      { label: '线速度', value: '45 m/min', standard: '100 — 130 m/min', normal: false },
      { label: '偏芯度', value: '0.08 mm', standard: '≤ 0.10 mm', normal: true },
    ],
    anomaly: '成缆段停机导致待料，线速度降至低速维持状态',
    correctiveAction: '成缆恢复后需重新做首件检验确认绝缘厚度',
  },
  {
    id: 'QT-A18-04',
    batchNo: 'BATCH-20260609-A18',
    orderId: 'SO-260609-18',
    productType: 'YJV-3x240',
    processStep: 'sheathing',
    processLabel: '护套',
    deviceCode: 'JSX-005',
    deviceName: '自动护套挤出机 #05',
    operator: '—',
    shift: '白班',
    startTime: '—',
    endTime: '—',
    timeRange: '未投产（待料）',
    sampleNo: '—',
    result: 'warning',
    params: [
      { label: '护套厚度', value: '—', standard: '1.8 ±0.15 mm', normal: true },
      { label: '挤出温度', value: '42.1 °C', standard: '待机 ≤ 80 °C', normal: true },
      { label: '线速度', value: '0 m/min', standard: '90 — 120 m/min', normal: false },
    ],
    anomaly: '上游成缆/绝缘堵塞，护套工序尚未接料',
  },
  {
    id: 'QT-A18-05',
    batchNo: 'BATCH-20260609-A18',
    orderId: 'SO-260609-18',
    productType: 'YJV-3x240',
    processStep: 'winding',
    processLabel: '收线',
    deviceCode: 'SXJ-002',
    deviceName: '双盘收线机 #02',
    operator: '—',
    shift: '白班',
    startTime: '—',
    endTime: '—',
    timeRange: '未投产（待料）',
    sampleNo: '—',
    result: 'warning',
    params: [
      { label: '收线张力', value: '—', standard: '32 — 50 N', normal: true },
      { label: '成卷米数', value: '0 m', standard: '≥ 500 m/盘', normal: false },
    ],
    anomaly: '批次尚未到达收线工序',
  },
  // —— BATCH-20260609-B21 正常批次 ——
  {
    id: 'QT-B21-01',
    batchNo: 'BATCH-20260609-B21',
    orderId: 'SO-260609-21',
    productType: 'BV-2.5',
    processStep: 'drawing',
    processLabel: '拉丝',
    deviceCode: 'LSJ-001',
    deviceName: '直进式拉丝机 #01',
    operator: '王工',
    shift: '白班',
    startTime: '06:30',
    endTime: '08:00',
    timeRange: '06:30 — 08:00',
    sampleNo: 'SP-B21-LS-01',
    result: 'pass',
    params: [
      { label: '拉丝张力', value: '39.8 N', standard: '38 — 55 N', normal: true },
      { label: '线速度', value: '420 m/min', standard: '400 — 500 m/min', normal: true },
      { label: '断线次数', value: '0 次', standard: '≤ 2 次/班', normal: true },
    ],
  },
  {
    id: 'QT-B21-02',
    batchNo: 'BATCH-20260609-B21',
    orderId: 'SO-260609-21',
    productType: 'BV-2.5',
    processStep: 'insulation',
    processLabel: '绝缘',
    deviceCode: 'JSX-004',
    deviceName: '精密绝缘挤塑机 #04',
    operator: '赵工',
    shift: '白班',
    startTime: '08:15',
    endTime: '11:30',
    timeRange: '08:15 — 11:30',
    sampleNo: 'SP-B21-JY-01',
    result: 'pass',
    params: [
      { label: '绝缘厚度', value: '0.82 mm', standard: '0.8 ±0.08 mm', normal: true },
      { label: '挤出温度', value: '178.2 °C', standard: '175 — 195 °C', normal: true },
      { label: '外径偏差', value: '±0.03 mm', standard: '±0.05 mm', normal: true },
    ],
  },
  {
    id: 'QT-B21-03',
    batchNo: 'BATCH-20260609-B21',
    orderId: 'SO-260609-21',
    productType: 'BV-2.5',
    processStep: 'winding',
    processLabel: '收线',
    deviceCode: 'SXJ-002',
    deviceName: '双盘收线机 #02',
    operator: '李工',
    shift: '白班',
    startTime: '11:45',
    endTime: '14:00',
    timeRange: '11:45 — 14:00',
    sampleNo: 'SP-B21-SX-01',
    result: 'pass',
    params: [
      { label: '收线张力', value: '38.5 N', standard: '32 — 50 N', normal: true },
      { label: '线速度', value: '380 m/min', standard: '350 — 420 m/min', normal: true },
      { label: '成卷米数', value: '820 m', standard: '≥ 500 m/盘', normal: true },
    ],
  },
  // —— BATCH-20260609-C25 拉丝阶段 ——
  {
    id: 'QT-C25-01',
    batchNo: 'BATCH-20260609-C25',
    orderId: 'SO-260609-25',
    productType: 'WDZ-BYJ',
    processStep: 'drawing',
    processLabel: '拉丝',
    deviceCode: 'LSJ-001',
    deviceName: '直进式拉丝机 #01',
    operator: '王工',
    shift: '白班',
    startTime: '09:00',
    endTime: '10:20',
    timeRange: '09:00 — 10:20',
    sampleNo: 'SP-C25-LS-01',
    result: 'pass',
    params: [
      { label: '拉丝张力', value: '40.5 N', standard: '38 — 55 N', normal: true },
      { label: '线速度', value: '435 m/min', standard: '400 — 500 m/min', normal: true },
      { label: '断线次数', value: '0 次', standard: '≤ 2 次/班', normal: true },
    ],
  },
];

export const INITIAL_WIP_ZONES: WipZone[] = [
  { id: 'wip-01', label: '拉丝待绞区', pos3d: { left: 200, top: 260 }, wipQty: 2.4, unit: 'km', orderId: 'SO-260609-18', orderLabel: 'YJV-3x240' },
  { id: 'wip-02', label: '成缆待绝缘', pos3d: { left: 560, top: 200 }, wipQty: 1.8, unit: 'km', orderId: 'SO-260609-18', orderLabel: 'YJV-3x240' },
  { id: 'wip-03', label: '收线盘 #2', pos3d: { left: 300, top: 400 }, wipQty: 3.2, unit: 'km', orderId: 'SO-260609-21', orderLabel: 'BV-2.5' },
];

export const BOTTLENECK_HEATMAP: BottleneckHeatCell[] = [
  { id: 'heat-01', label: '成缆 B 区', pos3d: { left: 320, top: 100, width: 240, height: 220 }, blockageCount: 12, intensity: 0.92 },
  { id: 'heat-02', label: '绝缘 C 区', pos3d: { left: 620, top: 80, width: 200, height: 180 }, blockageCount: 6, intensity: 0.55 },
  { id: 'heat-03', label: '护套待料区', pos3d: { left: 720, top: 240, width: 180, height: 160 }, blockageCount: 4, intensity: 0.38 },
];

export const INITIAL_MAINTENANCE_RECORDS: MaintenanceRecord[] = [
  { id: 'MR-01', deviceCode: 'CLJ-003', type: '故障检修', summary: '成缆段主轴超温停机，冷却阀排查', time: '2026-06-09 09:12', operator: '张工' },
  { id: 'MR-02', deviceCode: 'SXJ-002', type: '模具更换', summary: '收线模具 W12 磨损达85% 更换', time: '2026-06-07 14:20', operator: '李工' },
  { id: 'MR-03', deviceCode: 'LSJ-001', type: '预防维保', summary: '拉丝区季度润滑与张力校准', time: '2026-06-05 08:30', operator: '王工' },
  { id: 'MR-04', deviceCode: 'CLJ-003', type: '故障检修', summary: '束绞张力波动，传感器重新标定', time: '2026-06-03 16:45', operator: '张工' },
];

export const INITIAL_MOLD_RECORDS: MoldChangeRecord[] = [
  { id: 'MC-01', deviceCode: 'SXJ-002', moldCode: 'MOLD-W12', wearBefore: 85, time: '2026-06-07' },
  { id: 'MC-02', deviceCode: 'LSJ-001', moldCode: 'MOLD-D04', wearBefore: 78, time: '2026-05-28' },
  { id: 'MC-03', deviceCode: 'JSX-004', moldCode: 'MOLD-E21', wearBefore: 72, time: '2026-05-15' },
];

export const ENERGY_OVERVIEW: Record<'day' | 'week' | 'month', EnergyOverviewSnapshot> = {
  day: { totalKwh: 12800, totalCost: 8960, targetKwh: 12000, achievementRate: 93, yoyChange: -2.1, momChange: 6.4, peakKw: 286, avgPrice: 0.7 },
  week: { totalKwh: 86200, totalCost: 60340, targetKwh: 82000, achievementRate: 95, yoyChange: 1.8, momChange: 4.2, peakKw: 312, avgPrice: 0.7 },
  month: { totalKwh: 348000, totalCost: 243600, targetKwh: 330000, achievementRate: 94, yoyChange: 3.2, momChange: 2.8, peakKw: 328, avgPrice: 0.7 },
};

export const ENERGY_DEVICE_PROFILES: EnergyDeviceProfile[] = [
  { deviceCode: 'THL-002', deviceName: '精密退火高能熔融炉 #02', lineId: 'L0', lineName: '退火专线', area: '一车间 退火区', zone: '退火区', powerKw: 286, dailyKwh: 4200, loadPct: 88, level: 'high', isIdleWaste: false, focus3d: { offsetX: 70, offsetY: 40, scale: 1.08 } },
  { deviceCode: 'JSX-004', deviceName: '精密绝缘挤塑机 #04', lineId: 'L3', lineName: '绝缘 C 线', area: '二车间 挤出区 C', zone: '挤出区', powerKw: 132, dailyKwh: 2180, loadPct: 91, level: 'high', isIdleWaste: false, kwhPerKm: 28.4, focus3d: { offsetX: -70, offsetY: 60, scale: 1.08 } },
  { deviceCode: 'CLJ-003', deviceName: '高速行星成缆机 #03', lineId: 'L2', lineName: '成缆 B 线', area: '二车间 束绞区 B', zone: '成缆区', powerKw: 98, dailyKwh: 860, loadPct: 83, level: 'medium', isIdleWaste: false, kwhPerKm: 42.1, focus3d: { offsetX: -20, offsetY: 45, scale: 1.15 } },
  { deviceCode: 'LSJ-001', deviceName: '直进式拉丝机 #01', lineId: 'L1', lineName: '拉丝 A 线', area: '一车间 拉丝区 A', zone: '拉丝区', powerKw: 68, dailyKwh: 1240, loadPct: 68, level: 'medium', isIdleWaste: false, kwhPerKm: 18.2, focus3d: { offsetX: 90, offsetY: 50, scale: 1.1 } },
  { deviceCode: 'SXJ-002', deviceName: '双盘收线机 #02', lineId: 'L5', lineName: '收线 E 线', area: '一车间 收线区 B', zone: '收线区', powerKw: 45, dailyKwh: 980, loadPct: 72, level: 'medium', isIdleWaste: false, kwhPerKm: 15.6, focus3d: { offsetX: 40, offsetY: -30, scale: 1.08 } },
  { deviceCode: 'JSX-005', deviceName: '自动护套挤出机 #05', lineId: 'L4', lineName: '护套 D 线', area: '二车间 挤出区 D', zone: '挤出区', powerKw: 13.2, dailyKwh: 186, loadPct: 4, level: 'low', isIdleWaste: true, idleWasteKw: 13.2, kwhPerKm: 0, focus3d: { offsetX: -100, offsetY: -20, scale: 1.06 } },
];

export const ENERGY_ZONE_PROFILES: EnergyZoneProfile[] = [
  { id: 'zone-anneal', name: '退火高温区', area: '一车间 A区', totalKwh: 4200, powerKw: 286, level: 'high', pos3d: { left: 40, top: 160, width: 180, height: 160 }, focus3d: { offsetX: 70, offsetY: 40, scale: 1.08 } },
  { id: 'zone-extrude', name: '挤出熔融区', area: '二车间 C/D区', totalKwh: 2366, powerKw: 145, level: 'high', pos3d: { left: 600, top: 100, width: 280, height: 200 }, focus3d: { offsetX: -80, offsetY: 30, scale: 1.1 } },
  { id: 'zone-cable', name: '成缆绞合区', area: '二车间 B区', totalKwh: 860, powerKw: 98, level: 'medium', pos3d: { left: 300, top: 120, width: 260, height: 200 }, focus3d: { offsetX: -20, offsetY: 45, scale: 1.15 } },
  { id: 'zone-draw', name: '拉丝收线区', area: '一车间 A/B区', totalKwh: 2220, powerKw: 113, level: 'medium', pos3d: { left: 24, top: 200, width: 240, height: 180 }, focus3d: { offsetX: 60, offsetY: 20, scale: 1.06 } },
];

export const ENERGY_TREND_HOUR: EnergyTrendPoint[] = [
  { label: '06', energyKwh: 420, outputKm: 2.1 },
  { label: '08', energyKwh: 980, outputKm: 4.8 },
  { label: '10', energyKwh: 1520, outputKm: 7.2, isPeak: true },
  { label: '12', energyKwh: 1380, outputKm: 6.9 },
  { label: '14', energyKwh: 1240, outputKm: 6.1 },
  { label: '16', energyKwh: 1180, outputKm: 5.8 },
];

export const ENERGY_TREND_SHIFT: EnergyTrendPoint[] = [
  { label: '夜班', energyKwh: 3840, outputKm: 12.4 },
  { label: '白班', energyKwh: 8960, outputKm: 30.4, isPeak: true },
];

export const ENERGY_TREND_DAY: EnergyTrendPoint[] = [
  { label: '周一', energyKwh: 11800, outputKm: 38 },
  { label: '周二', energyKwh: 12100, outputKm: 40 },
  { label: '周三', energyKwh: 11900, outputKm: 39 },
  { label: '周四', energyKwh: 13200, outputKm: 42, isPeak: true },
  { label: '周五', energyKwh: 12800, outputKm: 41 },
  { label: '周六', energyKwh: 10500, outputKm: 35 },
  { label: '周日', energyKwh: 9800, outputKm: 32 },
];

export const ENERGY_ALERTS: EnergyAlertItem[] = [
  { id: 'EN-01', title: '5号护套挤出机待机空耗', description: '负载 4% 但持续通电 13.2kW，成缆停机导致无效空转已超 4h。', deviceCode: 'JSX-005', time: '09:15', timeRange: '05:00 — 09:15', spikeKw: 13.2, level: 'P2高危', kind: 'idle_waste', status: 'pending' },
  { id: 'EN-02', title: '退火炉尖峰段功率突增', description: '10:00—10:30 尖峰段功率 286kW，较基线 +25kW，疑似负荷调配异常。', deviceCode: 'THL-002', zoneId: 'zone-anneal', time: '10:22', timeRange: '10:00 — 10:30', spikeKw: 25, level: 'P2高危', kind: 'peak_over', status: 'pending' },
  { id: 'EN-03', title: '挤出区单位电耗偏高', description: '绝缘 C 线本批次 kWh/km 28.4，高于基准 24.0。', deviceCode: 'JSX-004', zoneId: 'zone-extrude', time: '08:45', timeRange: '08:00 — 09:00', spikeKw: 18, level: 'P3一般', kind: 'anomaly', status: 'pending' },
  { id: 'EN-04', title: '成缆区故障待机耗电', description: 'CLJ-003 故障停机但冷却/辅机仍维持 38kW 待机功耗。', deviceCode: 'CLJ-003', zoneId: 'zone-cable', time: '09:12', timeRange: '09:12 — 持续', spikeKw: 38, level: 'P3一般', kind: 'idle_waste', status: 'pending' },
];

export const ENERGY_CAPACITY_LINKS: EnergyCapacityLink[] = [
  { lineId: 'L1', lineName: '拉丝 A 线', batchNo: 'BATCH-20260609-A18', outputKm: 8.2, energyKwh: 1240, kwhPerKm: 151.2, benchmark: 160, status: 'good' },
  { lineId: 'L2', lineName: '成缆 B 线', batchNo: 'BATCH-20260609-A18', outputKm: 4.1, energyKwh: 860, kwhPerKm: 209.8, benchmark: 180, status: 'bad' },
  { lineId: 'L3', lineName: '绝缘 C 线', batchNo: 'BATCH-20260609-A18', outputKm: 3.6, energyKwh: 2180, kwhPerKm: 605.6, benchmark: 240, status: 'bad' },
  { lineId: 'L5', lineName: '收线 E 线', batchNo: 'BATCH-20260609-B21', outputKm: 6.4, energyKwh: 980, kwhPerKm: 153.1, benchmark: 165, status: 'good' },
];

export const ENERGY_SAVING_TIPS: EnergySavingTip[] = [
  { id: 'ST-1', title: '5号护套机深度节能休眠', description: '成缆恢复前关闭加热区，预计日省 120 kWh', savingKwh: 120, savingCost: 84, priority: 'high', deviceCode: 'JSX-005' },
  { id: 'ST-2', title: '尖峰段退火炉负荷调降', description: '10:00—12:00 退火功率下调 8%，利用谷段预热', savingKwh: 85, savingCost: 68, priority: 'high', deviceCode: 'THL-002' },
  { id: 'ST-3', title: '成缆故障待机辅机联控', description: 'CLJ-003 停机时自动切断非必要冷却循环', savingKwh: 45, savingCost: 32, priority: 'medium', deviceCode: 'CLJ-003' },
  { id: 'ST-4', title: '夜班挤出产线合并排班', description: 'BV-2.5 与 YJV 错峰生产，减少 2 台挤出机并行', savingKwh: 210, savingCost: 147, priority: 'medium' },
];

export const DEVICE_3D_LAYOUT: Record<string, { className: string; icon: string; zIndex: string }> = {
  'LSJ-001': { className: 'absolute left-16 top-[180px] w-44', icon: '⛓️', zIndex: 'z-10' },
  'SXJ-002': { className: 'absolute left-[24%] top-[330px] w-40', icon: '🌀', zIndex: 'z-10' },
  'CLJ-003': { className: 'absolute left-[44%] top-[190px] w-52', icon: '🔧', zIndex: 'z-20' },
  'JSX-004': { className: 'absolute right-[22%] top-[140px] w-44', icon: '🔥', zIndex: 'z-10' },
  'JSX-005': { className: 'absolute right-[44px] top-[300px] w-44', icon: '💤', zIndex: 'z-10' },
};
